FROM python:3.11-slim

WORKDIR /build

COPY . .

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

RUN pyinstaller --onefile --name ScreenAI main.py

CMD ["ls", "-la", "dist/"]
